export const ATIVIDADES_FETCH_REQUEST = 'ATIVIDADES/FETCH_REQUEST';
export const ATIVIDADES_FETCH_SUCCESS = 'ATIVIDADES/FETCH_SUCCESS';
export const ATIVIDADES_FETCH_ERROR = 'ATIVIDADES/FETCH_ERROR';

export const ATIVIDADES_UPLOAD_REQUEST = 'ATIVIDADES/UPLOAD_REQUEST';
export const ATIVIDADES_UPLOAD_SUCCESS = 'ATIVIDADES/UPLOAD_SUCCESS';
export const ATIVIDADES_UPLOAD_ERROR = 'ATIVIDADES/UPLOAD_ERROR';
